/*
	@File: fn_getButtons.sqf
  
	@Author: Jack "Scarso" Farhall
  
	@Description: Gets the buttons for this interaction...

	@Parameters:
		0 - TYPE: STRING - DES: The interaciton menu we're opening...
*/
scopeName "getButtons";
#include "..\..\..\..\script_macros.hpp"
if !(params [
	["_menu", "", [""]]
]) exitWith { systemChat "No Menu Provided" };

// Default variables...
private _title = "Unknown Interaction";
private _buttons = [];

switch (_menu) do {
	case "General": {
		// Checks for this menu...
		if (player getVariable ["Escorting", false]) exitWith { breakOut "getButtons" }; // Can't do these actions while escorting someone...
		
		_title = "Player Interaction"; // Set Title...

		// Setup buttons...
		_buttons pushBack ["Give Money", "createDialog ""RscMoneyMenu"""]; // Give Money Button...
	};

	case "Police": {
		_title = "Detained Interaction"; // Set Title...

		// Setup buttons...
		if (player getVariable ["isEscorting",false]) then {
			_buttons pushBack ["Stop Escorting", "[] call life_fnc_stopEscorting; closeDialog 0;"]; // Stop Escorting Button...
		} else {
			_buttons pushBack ["Give Money", "createDialog ""RscMoneyMenu"""]; // Give Money Button...
			_buttons pushBack ["Unrestrain", "[life_pInact_curTarget] call life_fnc_unrestrain; closeDialog 0;"]; // Unrestrain Action...
			_buttons pushBack ["Check Licenses", "[player] remoteExecCall [""life_fnc_licenseCheck"",life_pInact_curTarget]; closeDialog 0;"]; // Unrestrain Action...
			_buttons pushBack ["Search Player", "[life_pInact_curTarget] spawn life_fnc_searchAction; closeDialog 0;"]; // Unrestrain Action...
			_buttons pushBack ["Ticket Player", "[life_pInact_curTarget] call life_fnc_ticketAction;"]; // Ticket Action...
			_buttons pushBack ["Escort Player", "[life_pInact_curTarget] call life_fnc_escortAction; closeDialog 0;"]; // Escort Button...

			// Jail Button...
			{
				if ((player distance (getMarkerPos _x) <50)) exitWith { _buttons pushBack ["Send to prison", "[life_pInact_curTarget] call life_fnc_arrestAction; closeDialog 0;"] };
			} forEach LIFE_SETTINGS(getArray,"sendtoJail_locations");

			_buttons pushBack ["Put in vehicle", "[life_pInact_curTarget] call life_fnc_putInCar; closeDialog 0;"]; // Put in Vehicle Button...

			if (FETCH_CONST(life_coplevel) < (LIFE_SETTINGS(getNumber,"seize_minimum_rank"))) then { _buttons pushBack ["Seize Contraband", "[life_pInact_curTarget] spawn life_fnc_seizePlayerAction; closeDialog 0;"] }; // Seize Contraband Button...
		};
	};
};

[_title, _buttons] call FF(createMenu);